#!/bin/sh
mkdir -p "$HOME/.taskbar/"

function volumed() {
    FILE="$1"
    echo > "$FILE" 
    while
        echo "v:$(amixer sget Master | tr '\n' ' ' | cut -d "[" -f 2 | cut -d "%" -f 1)"
        inotifywait "$FILE"
    do :; done
}

function batteryd() {
    while
        echo "b:$(upower -i "/org/freedesktop/UPower/devices/battery_BAT0" \
            | grep "percentage:" | sed -E "s/[^0-9]//g")"
        sleep 60
    do :; done
}

function timed() {
    while
        echo "d:$(date '+%F %R')"
        sleep 5
    do :; done
}

function usage() {
    grep 'cpu' /proc/stat | sed -E "s/[ ]+/ /g" | cut -d ' ' -f 2,4,5
}

function cpud() {
    LAST=$(mktemp /tmp/cpu-last.XXXXXX)
    CURR=$(mktemp /tmp/cpu-curr.XXXXXX)
    usage > "$LAST"
    while
        usage > "$CURR"
        echo "c:$(paste -d " " "$CURR" "$LAST" | awk '{printf "%d %d %d\n",($1-$4),($2-$5),($3-$6)}' |\
            awk '{usage=($1+$2)*100/($1+$2+$3); printf " %3.0f",usage}')"
        cat "$CURR" > "$LAST"
        sleep 2
    do :; done
}

function memd() {
    while
        echo "m:$(cat /proc/meminfo | grep -E "Mem" | sed "s/[^0-9]//g" | tr '\n' ' ' | awk '{printf "%d %d",($1-$3),$1}')"
        sleep 2
    do :; done
}

(
    volumed "$HOME/.taskbar/volume-changed" &
    batteryd &
    timed &
    cpud &
    memd &
) | while IFS=':' read -r FIELD LINE; do
    case $FIELD in
        v) VOLUME="$LINE" ;;
        b) BATTERY="$LINE" ;;
        d) DATE="$LINE" ;;
        c) CPU="$LINE" ;;
        m) MEM="$LINE"
    esac
    BAR="%{l}"
    BAR+="%{l}"
    BAR+="%{c}"
    BAR+=$(echo "$VOLUME" | dbar -w 5 -l "vol")
    BAR+=$(echo "$BATTERY" | dbar -w 5 -l " | bat")
    BAR+=$(echo "$MEM" | dbar -w 5 -l " | mem")
    BAR+="%{c}"
    BAR+="%{r}"
    BAR+="$DATE"
    BAR+="%{r}"
    echo "$BAR"
done | lemonbar -p
