set-option global modelinefmt '%val{bufname}:%val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} '
set-option global tabstop 4
set-option global ui_options terminal_assistant=none terminal_set_title=true

# Relative line numbers
add-highlighter global/ number-lines     -relative -separator ' '
# Tab shown as ▸
add-highlighter global/ show-whitespaces -tab '▸' -tabpad ' ' -lf ' ' -spc ' '
# Trailing whitespace
add-highlighter global/ regex            '\h+$' 0:default,red
# Ruler at line 100
add-highlighter global/ column 100       default,bright-black

define-command ai -params 1 -docstring "" %{
    execute-keys -draft "|ai-code %opt{filetype} %arg[1]<ret>"
}

define-command ai-complete -docstring "" %{
    execute-keys -draft "|ai-code %opt{filetype} 'Complete the code'<ret>"
}

hook global BufWritePre .* %{
    try autoalign catch %{}
    try format catch %{
        try lsp-formatting-sync catch %{}
    }
    try lint catch %{}
}

colorscheme colors

