source "%val{config}/autoalign.kak"
source "%val{config}/autocomplete.kak"
source "%val{config}/ctags.kak"
source "%val{config}/filetype.kak"
source "%val{config}/format.kak"
source "%val{config}/fzf.kak"
source "%val{config}/keys.kak"
source "%val{config}/lint.kak"
source "%val{config}/lsp.kak"

colorscheme colors

set-option global modelinefmt '%val{bufname}:%val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} '
set-option global tabstop 4
set-option global scrolloff 4,4
set-option global ui_options terminal_assistant=none terminal_set_title=true

# Relative line numbers
add-highlighter global/ number-lines     -relative -separator ' '
# Tab shown as ▸
add-highlighter global/ show-whitespaces -tab '▸' -tabpad ' ' -lf ' ' -spc ' '
# Trailing whitespace
add-highlighter global/ regex            '\h+$' 0:default,red
# Ruler at line 100
add-highlighter global/ column 100       default,bright-black
