#!/bin/sh

eval "$(
    find ~/.config/environment.d/ -type f -exec cat '{}' '+' | sed \
        -e '/^ *$/d' \
        -e '/^ *#/d' \
        -e "s/\"/\"'\"'\"/g" \
        -e 's/^/export /' \
        -e 's/=/="/' \
        -e 's/$/"/'
)"

. ~/.bashrc
