#!/bin/sh

bspc rule -r "*"

for MONITOR in $(bspc query -M --names); do
    bspc monitor "$MONITOR" -d 1 2 3 4 5 6 7 8 9 0
done

bspc config normal_border_color "#$COLOR1"
bspc config active_border_color "#$COLOR2"
bspc config focused_border_color "#$COLOR4"

# Idk what these are. Use a weird color until i figure it out
bspc config presel_feedback_color "#$COLOR8"

bspc config split_ratio 0.54
bspc config border_width 1
bspc config window_gap 0
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc rule -a 'Zathura' state=tiled
bspc rule -a 'origin.exe' state=floating
bspc rule -a 'window' state=floating center=on sticky=on focus=on rectangle=1600x900+0+0
bspc rule -a 'fullscreen' state=fullscreen
bspc rule -a 'thunderbird' desktop=0
bspc rule -a 'discord' desktop=9
bspc rule -a 'vesktop' desktop=9
bspc rule -a 'Caprine' desktop=9
bspc rule -a 'steam' desktop=8

env | cut -d'=' -f1 | sed '/^_$/d' | xargs -d'\n' -n1 systemctl --user import-environment
systemctl --user start user-graphical-login.target
