#!/bin/sh

. "$HOME/.local/script/colors.sh"
bspc rule -r "*"

for MONITOR in $(bspc query -M --names); do
    bspc monitor "$MONITOR" -d 1 2 3 4 5 6 7 8 9 0
done

bspc config normal_border_color "#$COLOR1"
bspc config active_border_color "#$COLOR2"
bspc config focused_border_color "#$COLOR4"

# Idk what these are. Use a weird color until i figure it out
bspc config presel_feedback_color "#$COLOR8"

bspc config split_ratio 0.53
bspc config border_width 1
bspc config window_gap 0
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config top_padding 26

bspc rule -a 'MEGAsync' -o hidden=on
bspc rule -a 'Zathura' state=tiled
bspc rule -a 'origin.exe' state=floating
bspc rule -a 'window' state=floating center=on sticky=on focus=on rectangle=1280x720+0+0
bspc rule -a 'fullscreen' state=fullscreen

systemctl --user import-environment
systemctl --user start user-graphical-login.target
