eval %sh{kak-lsp --kakoune -s "$kak_session"}

set-option global tabstop 4
set-option global ui_options ncurses_assistant=off ncurses_set_title=true

add-highlighter global/ number-lines -relative -separator ' '
add-highlighter global/ show-whitespaces -tab '▸' -tabpad ' ' -lf ' ' -spc ' '
add-highlighter global/ regex '\h+$' 0:default,red

map global user c ':comment-line<ret>' -docstring 'Comment out line'
map global user y '<a-|>xsel -bi<ret>' -docstring 'Copy to system clipboard'
map global user p '!xsel -bo<ret>'     -docstring 'Paste from system clipboard'
map global user f ':fzf<ret>'          -docstring 'Fzf files'
map global user s ':fzf-rg<ret>'       -docstring 'Fzf content of files'
map global user S '!sort<ret>d'        -docstring 'Sort'

map global insert <pageup> '<a-;><c-b>'
map global insert <pagedown> '<a-;><c-f>'

map global normal "'" '<a-i>w*/<ret>'
map global normal 'z' ':w<ret>'

# Fix bad mappings for Danish keyboards
map global normal æ '<a-;>'

# Lang specific bindings
hook global WinSetOption filetype=zig %{
    map global insert 'æ' 'pub fn () void {}<esc><a-f>(;i'
}

# fzf
define-command open -params 1 %{
    terminal sh -c %sh{
        printf '%s | sed -E -e "s/^/evaluate-commands -client %s edit / ;
            s/:([0-9]+).*/\\nexecute-keys -client %s \\1g/" | kak -p "%s"' \
            "$1" "$kak_client" "$kak_client" "$kak_session"
    }
}

define-command fzf    %{ open fzf    }
define-command fzf-rg %{ open fzf-rg }

# Auto complete with tab
hook global InsertCompletionShow .* %{ map window insert <tab> <c-n> }
hook global InsertCompletionHide .* %{ map window insert <tab> <tab> }

# lsp hooks
hook global WinSetOption filetype=zig %{ lsp-enable-window }
hook global WinSetOption filetype=rust %{
    lsp-enable-window
    hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
    hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
    hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
    hook -once -always window WinSetOption filetype=.* %{
        remove-hooks window semantic-tokens
    }
}

# lint hooks
hook global BufWritePre .* %{ try lint catch %{} }
hook global WinSetOption filetype=sh %{ set-option window lintcmd 'shellcheck -f gcc' }

# formatter hooks
hook global BufWritePre .* %{ try format catch %{} }
hook global WinSetOption filetype=git-commit %{ set-option window formatcmd 'par "72rTbgqR" "B=.,?_A_a" "Q=_s>q|"' }
hook global WinSetOption filetype=json       %{ set-option window formatcmd "jq --indent %opt{tabstop} ." }
hook global WinSetOption filetype=python     %{ set-option window formatcmd 'yapf' }
hook global WinSetOption filetype=rust       %{ set-option window formatcmd 'rustfmt --edition 2018' }
hook global WinSetOption filetype=sh         %{ set-option window formatcmd "shfmt -i %opt{tabstop} -s -ci" }
hook global WinSetOption filetype=zig        %{ set-option window formatcmd 'zig-fix' }


def -hidden insert-c-n %{
    try %{
        lsp-snippets-select-next-placeholders
        exec '<a-;>d'
    } catch %{
        exec -with-hooks '<c-n>'
    }
}
map global insert <c-n> "<a-;>: insert-c-n<ret>"

# Colors

# For Code
face global keyword blue+b
face global attribute blue+b
face global type cyan+b
face global value cyan+b
face global string green+b
face global function yellow+b
face global operator white+b
face global variable white
face global meta cyan+b
face global module yellow+b
face global builtin yellow+b
face global comment bright-black+i
face global documentation comment
face global InlayHint bright-black+i

# For markup
face global title blue
face global header cyan
face global mono green
face global block magenta
face global link cyan
face global bullet cyan
face global list yellow

# builtin faces
face global Default default,default
face global PrimarySelection white,blue+fg
face global SecondarySelection black,blue+fg
face global PrimaryCursor black,white+fg
face global SecondaryCursor black,white+fg
face global PrimaryCursorEol black,cyan+fg
face global SecondaryCursorEol black,cyan+fg
face global LineNumbers default,default
face global LineNumberCursor default,default+r
face global MenuForeground white,blue
face global MenuBackground blue,white
face global MenuInfo cyan
face global Information black,yellow
face global Error black,red
face global StatusLine cyan,default
face global StatusLineMode yellow,default
face global StatusLineInfo blue,default
face global StatusLineValue green,default
face global StatusCursor black,cyan
face global Prompt yellow,default
face global MatchingChar default,default+b
face global Whitespace default,default+f
face global BufferPadding blue,default


