general {
    ignore_empty_input = true
}

background {
    color = rgb(20, 20, 20)
}

label {
    text = cmd[update:1000]echo "$(date '+%H:%M')"
    color = rgb(220, 220, 220) # text
    font_size = 60
    font_family = monospace
    position = 0, 260
}

label {
    text = $USER
    color = rgb(220, 220, 220) # text
    font_size = 20
    font_family = monospace
    position = 0, 60
}

input-field {
    size = 350, 50
    outline_thickness = 2
    outer_color = rgb(80, 80, 80)
    inner_color = rgb(20, 20, 20)
    font_color = rgb(220, 220, 220)
    font_family = monospace
    placeholder_text = <i>Password...</i>
    check_color = rgb(60, 120, 230)
    fail_color = rgb(240, 50, 50)
    fail_text = <i>$ATTEMPTS failed</i>
    capslock_color = rgb(200, 130, 30)
    position = 0, 0
    fade_on_empty = false
}
