#!/bin/sh
# TODO: Be able to search diffs of each commit instead of just the message
RES=$(sk --ansi -i -c "git reflog --all | rg '{}'" --preview 'git show $(echo {} | cut -f 1 -d " " )')
echo $RES | cut -f 1 -d " "
