#!/bin/sh
TMP=$(mktemp -d)
trap '{ kill $(jobs -p); wait; rm -rf -- "$TMP"; }' INT TERM HUP EXIT

git log --pretty=format:"%h" | while read -r in; do
    git show "$in" > "$TMP/$in"
done &

cd "$TMP" || exit 1
skrep | cut -f 1 -d ":"
