#!/usr/bin/env bash

source ~/.config/env
source <(starship init bash --print-full-init)
eval "$(direnv hook bash)"
eval "$(zoxide init bash)"

# if this is interactive shell, then bind hstr to Ctrl-r (for Vi mode check doc)
if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hstr -- \C-j"'; fi
# if this is interactive shell, then bind 'kill last command' to Ctrl-x k
if [[ $- =~ .*i.* ]]; then bind '"\C-xk": "\C-a hstr -k \C-j"'; fi

__cd_alias() {
    z "$@" || return
    timeout -k 0 0.1s exa
}

__ccd_alias() {
    mkdir "$@" || return
    __cd_alias "$@"
}

__paru_alias() {
    paru "$@" || return 1
    paru -Qqe >"$XDG_CONFIG_HOME/installed-programs"
}

__confirm() {
    command=$1
    shift
    printf "Are you sure you want to %s these [y/N]:\n" "${command}"
    for arg in "$@"; do
        printf "%s\n" "$arg"
    done

    read -r answer
    if [ "$answer" = "y" ]; then
        $command "$@"
    fi
}

__kak_alias() {
    cwd=$(pwd)
    session_id=$(echo "$cwd" | sha1sum | cut -d' ' -f1)

    KAK_LSP_FORCE_PROJECT_ROOT="$cwd" kak -c "$session_id" "$@" ||
        KAK_LSP_FORCE_PROJECT_ROOT="$cwd" kak -s "$session_id" "$@"
}

alias ..='__cd_alias ..'
alias ...='__cd_alias ../..'
alias .3='__cd_alias ../../..'
alias .4='__cd_alias ../../../..'

alias ccd='__ccd_alias'
alias cd='__cd_alias'
alias c='__cd_alias'

alias kak='__kak_alias'
alias paru='__paru_alias'

alias df='duf'
alias ll='exa -al'
alias ls='exa -a'

alias cp='cp -i'
alias man='fzf-man'
alias map='xargs -d"\n"'
alias mv='mv -i'
alias o='open'
alias r='ranger'

alias ab='autobuild'
alias cb='cargo build'
alias zb='zig build'

alias drag='dragon-drag-and-drop'
alias gdb='gdb -nh -x "$XDG_CONFIG_HOME/gdb/init"'
alias rg='rg --no-heading'
alias trr='transmission-remote 192.168.0.119'

alias ga='git add'
alias gap='git add --patch'
alias gb='git branch --all'
alias gca='git commit --amend'
alias gc='git commit'
alias gcl='git clone --recursive'
alias gcn='git commit --no-verify'
alias gd='git difftool'
alias gds='git difftool --staged'
alias gf='git fetch'
alias gl='git log --graph --oneline'
alias gp='git push'
alias gpl='git pull'
alias grbc='git rebase --continue'
alias grb='git rebase'
alias grs='__confirm "git restore"'
alias grss='__confirm "git restore --staged"'
alias grsp='git restore --patch'
alias gs='git status'
alias gsh='git stash'
alias gsw='git switch'
