#!/usr/bin/env bash

eval "$(
    sed \
        -e '/^ *$/d' \
        -e '/^ *#/d' \
        -e "s/\"/\"'\"'\"/g" \
        -e 's/^/export /' \
        -e 's/=/="/' \
        -e 's/$/"/' ~/.config/environment.d/env.conf
)"

source <(starship init bash --print-full-init)
eval "$(fzf --bash)"
eval "$(direnv hook bash)"
eval "$(zoxide init bash)"

__cd_alias() {
    z "$@" || return
    timeout -k 0 0.1s eza
}

__yay_alias() {
    yay "$@" || return 1
    yay -Qqe >"$XDG_CONFIG_HOME/installed-programs"
    rg -xF -f \
        "$XDG_CONFIG_HOME/essential-programs" \
        "$XDG_CONFIG_HOME/installed-programs" |
        sponge "$XDG_CONFIG_HOME/essential-programs"
    rg -vxF -f \
        "$XDG_CONFIG_HOME/essential-programs" \
        "$XDG_CONFIG_HOME/installed-programs" |
        sponge "$XDG_CONFIG_HOME/installed-programs"
}

__dipm_alias() {
    dipm "$@" || return 1
    dipm list installed | sort | cut -f1 >"$XDG_CONFIG_HOME/dipm-installed-programs"
}

__kak_alias() {
    tmux new-session kakoune "$@"
}

alias ..='__cd_alias ..'
alias ...='__cd_alias ../..'

alias cd='__cd_alias'
alias cdt='__cd_alias "$(mktemp -d)"'

alias dipm='__dipm_alias'
alias kak='__kak_alias'
alias yay='__yay_alias'

alias df='df -h'
alias ll='eza --all --long --group --header'
alias ls='eza -a'
alias man='kak-man'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'

alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'

alias drag='dragon-drop'
alias rg='rg --no-heading'

alias ga='git add'
alias gap='git add --patch'
alias gb='git branch --all'
alias gca='git commit --amend'
alias gc='git commit'
alias gcl='git clone --recursive'
alias gcn='git commit --no-verify'
alias gd='git difftool'
alias gds='git difftool --staged'
alias gf='git fetch'
alias gl='git log --graph --oneline'
alias glp='git log -p'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpl='git pull --prune'
alias grbc='git rebase --continue'
alias grb='git rebase'
alias grs='ask git restore'
alias grss='ask git restore --staged'
alias grsp='git restore --patch'
alias grssp='git restore --staged --patch'
alias gs='git status'
alias gsh='git stash'
alias gsw='git switch'

tealdeer -l | sort -R | while read -r page; do
    if ! tealdeer "$page" | grep 'This command is an alias of' >/dev/null; then
        tealdeer "$page"
        break
    fi
done
