#!/usr/bin/env bash

source <(starship init bash --print-full-init)
eval "$(fzf --bash)"
eval "$(direnv hook bash)"
eval "$(zoxide init bash)"

__cd_alias() {
    z "$@" || return
    timeout -k 0 0.1s eza
}

__paru_alias() {
    paru "$@" || return 1
    paru -Qqe >"$XDG_CONFIG_HOME/installed-programs"
    rg -xF -f \
        "$XDG_CONFIG_HOME/essential-programs" \
        "$XDG_CONFIG_HOME/installed-programs" |
        sponge "$XDG_CONFIG_HOME/essential-programs"
    rg -vxF -f \
        "$XDG_CONFIG_HOME/essential-programs" \
        "$XDG_CONFIG_HOME/installed-programs" |
        sponge "$XDG_CONFIG_HOME/installed-programs"
}

__confirm() {
    command=$1
    shift
    printf "Are you sure you want to %s these [y/N]:\n" "${command}"
    for arg in "$@"; do
        printf "%s\n" "$arg"
    done

    read -r answer
    if [ "$answer" = "y" ]; then
        $command "$@"
    fi
}

__kak_alias() {
    cwd=$(pwd)
    session_id=$(echo "$cwd" | sha1sum | cut -d' ' -f1)

    KAK_LSP_FORCE_PROJECT_ROOT="$cwd" kak -c "$session_id" "$@" ||
        KAK_LSP_FORCE_PROJECT_ROOT="$cwd" kak -s "$session_id" "$@"
}

alias ..='__cd_alias ..'
alias ...='__cd_alias ../..'

alias cd='__cd_alias'

alias kak='__kak_alias'
alias paru='__paru_alias'

alias df='df -h'
alias ll='eza -al'
alias ls='eza -a'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'

alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'

alias drag='dragon-drag-and-drop'
alias rg='rg --no-heading'

alias ga='git add'
alias gap='git add --patch'
alias gb='git branch --all'
alias gca='git commit --amend'
alias gc='git commit'
alias gcl='git clone --recursive'
alias gcn='git commit --no-verify'
alias gd='git difftool'
alias gds='git difftool --staged'
alias gf='git fetch'
alias gl='git log --graph --oneline'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpl='git pull --prune'
alias grbc='git rebase --continue'
alias grb='git rebase'
alias grs='__confirm "git restore"'
alias grss='__confirm "git restore --staged"'
alias grsp='git restore --patch'
alias gs='git status'
alias gsh='git stash'
alias gsw='git switch'

while true; do
    page=$(tealdeer -l | sort -R | head -n1)
    if ! tealdeer "$page" | grep 'This command is an alias of' >/dev/null; then
        tealdeer "$page" --color always 2>/dev/null | head -n 12
        break
    fi
done

cache -s "$(date +%Y-%m-%d)" -- curl -s 'https://wttr.in?nFQ' 2>/dev/null |
    tail -n 30
