#!/bin/sh

export PATH="\
/usr/share/bcc/tools/:\
/usr/lib/ccache/bin/:\
$HOME/.cache/cargo/bin:\
$HOME/.local/bin:\
$HOME/.local/script:\
$PATH"

# Bash history
export HISTSIZE=9999999
export HISTFILESIZE=9999999
export HISTCONTROL='ignorespace:ignoredups:erasedups'
export PROMPT_COMMAND='history -a; history -c; history -r; history -n'

# Programs
export BROWSER='firefox'
export EDITOR='kak'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export PAGER='less'
export READER='zathura'
export TERMINAL='st'
export WINDOW="$TERMINAL -c window"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export CARGO_HOME="$XDG_CACHE_HOME/cargo"
export CCACHE_DIR="$XDG_CACHE_HOME/ccache"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"
export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"

export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/go"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export HISTFILE="$XDG_DATA_HOME/bash_history"
export LESSHISTFILE="$XDG_DATA_HOME/less/history"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"
export WINEPREFIX="$XDG_DATA_HOME/wine"
export _ZL_DATA="$XDG_DATA_HOME/zlua"

export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/notmuchrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export XINITRC="$XDG_CONFIG_HOME/xorg/init"

export CM_LAUNCHER='fzf'
export FZF_DEFAULT_COMMAND='fd -H --type f -S -10m'
export FZF_DEFAULT_OPTS='--no-info --color=16'
export GST_DEBUG_DUMP_DOT_DIR=dots
export HSTR_CONFIG='hicolor,prompt-bottom,raw-history-view'
export LESS='-R'
export MCFLY_FUZZY=true
export MCFLY_RESULTS=20
export NNN_OPENER='open.sh'
export QT_QPA_PLATFORMTHEME='gtk2'
export RUST_BACKTRACE=1
export TS_SLOTS=10000

export GTK_THEME="Breeze:dark"
export TERMINFO_DIRS="$TERMINFO:/usr/share/terminfo"

export RS_SERIAL_DEFAULT=739112060855
