aws.disabled = true
azure.disabled = true
battery.disabled = true
cmake.disabled = true
cobol.disabled = true
conda.disabled = true
crystal.disabled = true
dart.disabled = true
deno.disabled = true
docker_context.disabled = true
dotnet.disabled = true
elixir.disabled = true
elm.disabled = true
erlang.disabled = true
fill.disabled = true
gcloud.disabled = true
golang.disabled = true
helm.disabled = true
hg_branch.disabled = true
hostname.disabled = true
java.disabled = true
jobs.disabled = true
julia.disabled = true
kotlin.disabled = true
kubernetes.disabled = true
localip.disabled = true
lua.disabled = true
memory_usage.disabled = true
nim.disabled = true
nix_shell.disabled = true
nodejs.disabled = true
ocaml.disabled = true
openstack.disabled = true
package.disabled = true
perl.disabled = true
php.disabled = true
pulumi.disabled = true
purescript.disabled = true
python.disabled = true
red.disabled = true
rlang.disabled = true
ruby.disabled = true
rust.disabled = true
scala.disabled = true
shell.disabled = true
shlvl.disabled = true
singularity.disabled = true
status.disabled = true
swift.disabled = true
terraform.disabled = true
time.disabled = true
username.disabled = true
vagrant.disabled = true
vcsh.disabled = true
vlang.disabled = true
zig.disabled = true

[character]
error_symbol = '[\$](bold red)'
format = '$symbol '
success_symbol = '[\$](bold green)'
vicmd_symbol = '[\$](bold green)'

[cmd_duration]
min_time = 0
show_milliseconds = true

[directory]
read_only_style = 'bold red'
style = 'bold blue'
truncation_length = 3

[git_branch]
style = 'bold bright-black'
truncation_length = 20

[git_status]
ahead = '>'
behind = '<'
modified = '*'

