format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$memory_usage\
$cmd_duration\
$line_break\
$character"""

[character]
error_symbol = '[\$](bold red)'
format = '$symbol '
success_symbol = '[\$](bold green)'
vicmd_symbol = '[\$](bold green)'

[cmd_duration]
disabled = false

[directory]
read_only_style = 'bold red'
style = 'bold blue'
truncation_length = 3

[git_branch]
style = 'bold bright-black'
truncation_length = 20

[git_status]
ahead = '>'
behind = '<'
modified = '*'

