format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$memory_usage\
$cmd_duration\
$line_break\
$character"""

[character]
format = '$symbol '
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[\$](bold green)'
vimcmd_visual_symbol = '[\$](bold yellow)'
vimcmd_replace_symbol = '[\$](bold purple)'
vimcmd_replace_one_symbol = '[\$](bold purple)'

[cmd_duration]
disabled = false

[directory]
read_only_style = 'bold red'
style = 'bold blue'

[git_branch]
style = 'bold bright-black'
truncation_length = 20
