#!/bin/sh

#### Colors ####

SCHEME="$HOME/.local/script/colors.sh"
. "$SCHEME"

#### bspwm config ####

bspc rule -r "*"

for MONITOR in $(bspc query -M --names); do
    bspc monitor "$MONITOR" -d 1 2 3 4 5 6 7 8 9 0
done

bspc config normal_border_color "#$COLOR1"
bspc config active_border_color "#$COLOR2"
bspc config focused_border_color "#$COLOR4"

# Idk what these are. Use a weird color until i figure it out
bspc config presel_feedback_color "#$COLOR8"

bspc config split_ratio           0.55
bspc config border_width          1
bspc config window_gap            0
bspc config focus_follows_pointer true

bspc rule -a MEGAsync desktop=^10 state=floating
bspc rule -a pick-dialog state=floating
bspc rule -a Zathura state=tiled

#### Language ####


#### Generate symlinks ####

ln -sf "$HOME/.local/script/open" "$HOME/.local/script/xdg-open"

#### Generate themes #####

mkfile() {
    mkdir -p "$(dirname "$1")"
    touch "$1"
    echo "$1"
}

TEMPLATE_DIR="$HOME/.config/template"
base16.sh "$SCHEME" "$TEMPLATE_DIR/dunstrc" > "$(mkfile "$HOME/.config/dunst/dunstrc")" &
base16.sh "$SCHEME" "$TEMPLATE_DIR/.gtkrc-2.0" > "$(mkfile "$HOME/.config/gtk-2.0/gtkrc-2.0")" &
base16.sh "$SCHEME" "$TEMPLATE_DIR/.Xresources" > "$(mkfile "$HOME/.config/xorg/resources")" &
wait
gtkrc-reload
xrdb -merge "$HOME/.config/xorg/resources"

#### Auto start ####

# programs we restart when we restart the wm
restart.sh bar.sh
restart.sh dunst
restart.sh sxhkd -r /tmp/sxhkd.log

#### Reload ####

{
    echo "$HOME/.config/sxhkd/sxhkdrc"
    echo "$HOME/.config/bspwm/bspwmrc"
    echo "$HOME/.local/script/bar-info.sh"
    echo "$HOME/.local/script/bar-mk.sh"
    echo "$HOME/.local/script/bar.sh"
    echo "$HOME/.local/script/base16.sh"
    echo "$HOME/.local/script/restart.sh"
    echo "$SCHEME"
    find "$TEMPLATE_DIR"
} | restart.sh entr -p bspc wm -r
