#!/bin/sh

for MONITOR in $(bspc query -M --names); do
    bspc monitor "$MONITOR" -d 1 2 3 4 5 6 7 8 9 0
done

eval "$(colors.sh)"

bspc config normal_border_color "$COLOR1"
bspc config focused_border_color "$COLOR4"
bspc config active_border_color "$COLOR4"

# Idk what these are. Use a weird color until i figure it out
bspc config presel_feedback_color "$COLOR8"

bspc config automatic_scheme     alternate

bspc config split_ratio          0.55
bspc config border_width         2
bspc config window_gap           0

setxkbmap -layout "dk"
ln -s "$HOME/.local/script/open.sh" "$HOME/.local/script/xdg-open"

# Generate themes. Having this here, allows us to hot reload themes which is nice
SCHEME="$HOME/colors.yaml"
ALACRITTY_TEMPLATE="$HOME/templates/alacritty.yml"
ROFI_TEMPLATE="$HOME/templates/theme.rasi"
VSCODIUM_TEMPLATE="$HOME/templates/settings.json"
XRESOURCES_TEMPLATE="$HOME/templates/.Xresources"
base16.sh "$SCHEME" "$ALACRITTY_TEMPLATE" > "$HOME/.config/alacritty/alacritty.yml" &
base16.sh "$SCHEME" "$VSCODIUM_TEMPLATE" > "$HOME/.config/VSCodium/User/settings.json" &
base16.sh "$SCHEME" "$ROFI_TEMPLATE" > "$HOME/.config/rofi/theme.rasi" &
base16.sh "$SCHEME" "$XRESOURCES_TEMPLATE" > "$HOME/.Xresources"

# programs we run on startup and never restart
runonce.sh megasync
runonce.sh sxhkd -r /tmp/sxhkd.log

# programs we restart when we restart the wm
restart.sh wall.sh
restart.sh bar.sh

restart.sh dunst

# reload sxhkd config when it changes
echo "$HOME/.config/sxhkd/sxhkdrc" | restart.sh entr -p pkill -USR1 -x sxhkd

# restart wm when certain configs changes
(
    echo "$HOME/.config/bspwm/bspwmrc"
    echo "$HOME/.local/script/bar-info.sh"
    echo "$HOME/.local/script/bar-mk.sh"
    echo "$HOME/.local/script/bar.sh"
    echo "$HOME/.local/script/base16.sh"
    echo "$HOME/.local/script/restart.sh"
    echo "$HOME/.local/script/runonce.sh"
    echo "$SCHEME"
    echo "$ALACRITTY_TEMPLATE"
    echo "$VSCODIUM_TEMPLATE"
    echo "$ROFI_TEMPLATE"
    echo "$XRESOURCES_TEMPLATE"
) | restart.sh entr -p bspc wm -r
