#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

setxkbmap -layout "dk"

# programs we run on startup and never restart
runonce.sh megasync &
runonce.sh sxhkd -r /tmp/sxhkd.log &

# programs we restart when we restart the wm
# TODO: runone.sh does not work on runnable scripts. They have to be invoked by
#       /bin/sh for it to work correctly
restart.sh /bin/sh "$HOME/.local/script/wall.sh" &
restart.sh /bin/sh "$HOME/.local/script/bar.sh" &

restart.sh compton &

# reload sxhkd config when it changes
echo "$HOME/.config/sxhkd/sxhkdrc" | restart.sh entr -p pkill -USR1 -x sxhkd &

# restart wm when certain configs changes
(
    echo "$HOME/.config/bspwm/bspwmrc"
    echo "$HOME/.config/compton/compton.conf"
    echo "$HOME/.local/script/bar.sh"
) | restart.sh entr -p bspc wm -r &
