#!/bin/sh

#### X Settings ####

xset r rate 300 50
xset s off
xset s off -dpms
setxkbmap -layout "dk"
xrandr --output HDMI-0 --mode 1920x1080 --right-of DP-0 \
    --output DP-0 --primary --mode 2560x1440 --rate 144

xrdb -merge "$XDG_CONFIG_HOME/xorg/resources"

{
#### Watches ####

tsp sh -c 'generate depends xresources | entr -np generate xresources'
tsp sh -c 'generate depends dunstrc | entr -np generate dunstrc'
tsp sh -c 'generate depends kitty | entr -np generate kitty'
tsp sh -c 'generate depends gtk_theme | entr -np generate gtk_theme'
tsp sh -c '{
    echo "$HOME/.config/bspwm/bspwmrc"
    echo "$(which colors.sh)"
} | entr -np bspc wm -r'
tsp sh -c 'echo "$XDG_CONFIG_HOME/sxhkd/sxhkdrc" | entr -nr sxhkd -r /tmp/sxhkd.log'
tsp sh -c 'echo "$XDG_CONFIG_HOME/dunst/dunstrc" | entr -nr dunst'
tsp sh -c '{
    echo "$(which lemonbar-maker)"
    echo "$(which bar.sh)"
    echo "$XDG_CONFIG_HOME/xorg/resources"
} | entr -nr bar.sh'

#### Daemons ####

rm -r .mash
tsp redshift
tsp transmission-daemon -f
tsp megasync
tsp xbanish
tsp wall.sh "$HOME/mega/images/wallpapers"
TWITCH_TOKEN=$(pass show twitch-oath) tsp twitchbot.sh -c 'komarispaghetti' -n 'komarispaghetti'
MASH_TOKEN=$(pass show discord-token) tsp mash start

#### Task that are nice to just have run on startup ####

tsp mbsync -a -c "$HOME/.config/isync/mbsyncrc"
tsp anilist fetch

} &

exec bspwm

