#!/usr/bin/env sh

#### Setup variables and dirs ####
template_dir="$HOME/.config/template"
colors="$HOME/.local/script/colors.sh"

xresources="$XDG_CONFIG_HOME/xorg/resources"
dunstrc="$XDG_CONFIG_HOME/dunst/dunstrc"
gtk_theme="$HOME/.themes/$GTK_THEME"

mkdir -p "$XDG_CONFIG_HOME/xorg"
mkdir -p "$XDG_CONFIG_HOME/dunst"

#### X Settings ####

xset r rate 300 50
xset s off
xset s off -dpms
setxkbmap -layout "dk"
xrandr --output HDMI-0 --mode 1920x1080 --right-of DP-0 \
    --output DP-0 --primary --mode 2560x1440 --rate 144

#### Generate themes that don't exist ####

ln -sf "$HOME/.local/script/open" "$HOME/.local/script/xdg-open"
[ -f "$xresources" ] || generate xresources
[ -f "$dunstrc" ]    || generate dunstrc
[ -d "$gtk_theme" ]  || generate gtk_theme
xrdb -merge "$xresources"

#### Watches ####

{
    echo "$template_dir/.Xresources"
    echo "$HOME/.local/script/generate"
    echo "$HOME/.local/script/base16.sh"
    echo "$colors"
} | entr -np generate xresources &

{
    echo "$template_dir/dunstrc"
    echo "$HOME/.local/script/generate"
    echo "$HOME/.local/script/base16.sh"
    echo "$colors"
} | entr -np generate dunstrc &

{
    find "$template_dir/$GTK_THEME" -type f
    echo "$HOME/.local/script/generate"
    echo "$HOME/.local/script/base16.sh"
    echo "$colors"
} | entr -np generate gtk_theme &

{
    echo "$(which lemonbar-maker)"
    echo "$HOME/.local/script/bar.sh"
    echo "$xresources"
} | entr -nr bar.sh &

{
    echo "$HOME/.config/bspwm/bspwmrc"
    echo "$colors"
} | entr -np bspc wm -r &

echo "$XDG_CONFIG_HOME/sxhkd/sxhkdrc" | entr -nr sxhkd -r /tmp/sxhkd.log &
echo "$dunstrc" | entr -nr dunst &

#### Other programs ####

mbsync -a -c "$HOME/.config/isync/mbsyncrc" &
megasync &
redshift &
transmission-daemon -f &
wall.sh "$HOME/mega/images/wallpapers" >/tmp/wall.sh.log 2>/tmp/wall.sh.log &
xbanish &

exec bspwm

