#!/bin/sh

cache_dir="$HOME/.cache/anilist"
database_file="$cache_dir/database.json"

fzf2() { fzf -m --tiebreak begin --tabstop 4 "$@"; }

[ -f "$database_file" ] || anilist fetch
anilist fetch &

command=$1

while true; do
    picks=$(mktemp)
    case $command in
        browse) anilist database | fzf2 | cut -f5,6 > "$picks" ;;
        pick) anilist list | fzf2 | cut -f5,6 > "$picks" ;;
        *)
            wait
            rm "$picks"
            exit 0
            ;;
    esac
    [ -s "$picks" ] || { rm "$picks"; break; }

    while true; do
        choice=$(printf '
complete
drop
plan_to_watch
put_on_hold
start_watching
torrent
view
' | sed '/^$/d' | fzf | cut -f1)
        case $choice in
            view) cut -f2 "$picks" | xargs -d '\n' setsid -f "$BROWSER" 2>/dev/null >/dev/null ;;

            torrent) cut -f1 "$picks" |
                sed -e 's/ /+/g' -e 's#^#https://nyaa.si/?q=#' |
                xargs -d '\n' setsid -f "$BROWSER" 2>/dev/null >/dev/null
            ;;
            complete|drop|plan_to_watch|put_on_hold|start_watching)
                cut -f2 "$picks" | xargs -d'\n' anilist "$choice" 2>/tmp/dump ;;
            *) break ;;
        esac
    done

    rm "$picks";
done

