#!/bin/sh

fzf2() {
    size=$(tput cols)
    fzf -m -d '\t' --tiebreak begin --with-nth=1,2,3,4,5 \
        --preview "kitty icat --clear --transfer-mode file; \
            kitty icat --place \
            \${FZF_PREVIEW_COLUMNS}x\${FZF_PREVIEW_LINES}@\$(($size - FZF_PREVIEW_COLUMNS))x0 \
            --scale-up --transfer-mode file {7}" \
        --preview-window right,38% \
        "$@"
}

command=$1
search=$2

while true; do
    picks=$(mktemp)
    case $command in
        database) anilist database | rg "$search" | fzf2 | cut -f5,6 >"$picks" ;;
        list) anilist list | rg "$search" | fzf2 --tabstop 4 | cut -f5,6 >"$picks" ;;
        *)
            wait
            rm "$picks"
            exit 0
            ;;
    esac
    [ -s "$picks" ] || {
        rm "$picks"
        break
    }

    while true; do
        choice=$(printf '
complete
drop
plan_to_watch
put_on_hold
start_watching
update
remove
watch_episode
torrent
view
' | sed '/^$/d' | fzf | cut -f1)
        case $choice in
            view) cut -f2 "$picks" | xargs -d '\n' tsp "$BROWSER" ;;

            torrent)
                cut -f1 "$picks" |
                    sed -e 's/ /+/g' -e 's#^#https://nyaa.si/?q=#' |
                    xargs -d '\n' tsp "$BROWSER"
                ;;
            complete | drop | plan_to_watch | put_on_hold | start_watching | update | remove | watch_episode)
                cut -f2 "$picks" | xargs -d'\n' anilist "$choice" 2>/tmp/dump
                ;;
            *) break ;;
        esac
    done

    rm "$picks"
done
