#!/bin/sh

cmd=$*
[ -z "$cmd" ] && [ -f 'Cargo.toml' ] &&
    cmd='cargo clippy && cargo build'
[ -z "$cmd" ] && [ -f 'build.zig' ] &&
    cmd='zig build'

fd '\.(h|hh|hpp|c|cc|cpp|rs|toml|zig)' | entr -crs "$cmd"
