#!/usr/bin/env -S sh
pattern=$1
shift;

endian='l'
signed='u'
size=8

for i in $(echo "$pattern" | tr ' ' '\n'); do
    case $i in
        lu*|bu*|li*|bi*)
            endian="$(echo "$i" | cut -b1)"
            signed="$(echo "$i" | cut -b2)"
            size="$(echo "$i" | cut -b3-)"
            ;;
        *)
            printf "%0$((size/4))x\n" "$i" | fold -w2 | case $endian in
                l) tac ;;
                b) cat ;;
            esac | sed -e 's/^/\\\\x/' | tr -d '\n'
            ;;
    esac
done | xargs -I% rg --no-heading --no-line-number --only-matching \
    --case-sensitive --multiline --text --byte-offset '(?-u)%' $@

