#!/bin/sh
echo "" | fzf -d ':' --no-extended --ansi \
    --bind "change:reload:rg $@ --fixed-strings --hidden --line-number {q} || true" \
    --preview 'bat --style=numbers --pager=never --color=always --line-range={2}: --highlight-line={2} {1}'
