#!/usr/bin/sh

template_dir="$HOME/.config/template"
colors="$HOME/.local/script/colors.sh"

xresources="$XDG_CONFIG_HOME/xorg/resources"
dunstrc="$XDG_CONFIG_HOME/dunst/dunstrc"
gtk_theme="$HOME/.themes/$GTK_THEME"
gtk_template="$template_dir/$GTK_THEME"

case $1 in
    xresources)
        base16.sh "$colors" "$template_dir/.Xresources" > "$xresources"
        xrdb -merge "$xresources"
        ;;
    dunstrc)
        base16.sh "$colors" "$template_dir/dunstrc" > "$dunstrc"
        ;;
    gtk_theme)
        mkdir -p "$HOME/.themes/"
        cp -r "$gtk_template" "$HOME/.themes/"

        rg -aFl '{{base' "$gtk_template" |
            sd -s "$gtk_template/" '' |
        while read -r file; do
            base16.sh "$colors" "$gtk_template/$file" > "$gtk_theme/$file"
        done
        gtkrc-reload
        ;;
esac

