#!/bin/sh

colors="$(which colors.sh)"
template_dir="$HOME/.config/template"

xresources="$XDG_CONFIG_HOME/xorg/resources"
dunstrc="$XDG_CONFIG_HOME/dunst/dunstrc"
kittyrc="$XDG_CONFIG_HOME/kitty/kitty.conf"
gtk_theme="$HOME/.themes/$GTK_THEME"
gtk_template="$template_dir/$GTK_THEME"

case $1 in
    xresources)
        mkdir -p "$(dirname "$xresources")"
        base16.sh "$colors" "$template_dir/.Xresources" >"$xresources"
        xrdb -merge "$xresources"
        ;;
    dunstrc)
        mkdir -p "$(dirname "$dunstrc")"
        base16.sh "$colors" "$template_dir/dunstrc" >"$dunstrc"
        ;;
    kitty)
        mkdir -p "$(dirname "$kittyrc")"
        base16.sh "$colors" "$template_dir/kitty.conf" >"$kittyrc"
        ;;
    gtk_theme)
        mkdir -p "$HOME/.themes/"
        cp -r "$gtk_template" "$HOME/.themes/"

        rg -aFl '{{base' "$gtk_template" |
            sd -s "$gtk_template/" '' |
            while read -r file; do
                base16.sh "$colors" "$gtk_template/$file" >"$gtk_theme/$file"
            done
        ;;
    depends)
        printf "%s\n%s\n%s\n" \
            "$(realpath "$0")" \
            "$(which base16.sh)" \
            "$colors"
        case $2 in
            xresources) echo "$template_dir/.Xresources" ;;
            dunstrc) echo "$template_dir/dunstrc" ;;
            kitty) echo "$template_dir/kitty.conf" ;;
            gtk_theme) find "$gtk_template" -type f ;;
        esac
        ;;
esac
