#!/bin/sh

while [ -n "$1" ]; do
    case $1 in
        --) shift; break ;;
        -s|--string-mode) string_mode='-s' ;;
        -h|--help) usage; exit 0 ;;
        -*) usage; exit 1 ;;
        *) break ;;
    esac
    shift
done

pattern=$1
replacement=$2
shift; shift;

find "$@" -type f | while read -r file; do
    tmp=$(mktemp)
    sd "$string_mode" -p "$pattern" "$replacement" "$file" > "$tmp"
    diff -u "$file" "$tmp"
    [ $? = 2 ] && exit 1

    rm "$tmp"
done

