#!/bin/sh

input=$(mktemp)
trap 'rm "$input"' EXIT

for arg in "$@"; do
    printf '%s\n' "$arg"
done | paste - - >"$input"

cut -f2 "$input" | xargs -d '\n' open ||
    cut -f1 "$input" | xargs -d '\n' open || exit 1
cut -f1 "$input" | sfeed_markread read
