#!/bin/sh -e

self=$0

# The two first ifs ensures that we only ever get 1 file as input, which
# will make the logic afterwards simpler.
if [ "$#" = 0 ]; then
    tmp=$(mktemp)
    trap 'rm "$tmp"' EXIT
    cat - >"$tmp"

    "$self" "$tmp"
    cat "$tmp"
    exit 0
fi

zig ast-check --color off "$@" 2>&1
