#!/bin/sh -e

file=$(mktemp)
zig fmt --stdin >"$file"

# Sort global constants
{
    grep -E -n '^(pub\s+)?const.*;$' "$file" | cut -d: -f1 |
        ranges | sed 's/$/!sort/'
    echo 'x'
} | ex -s "$file"

cat "$file"
rm "$file"
