#!/bin/sh

diff=$(cat -)

echo 'You are a code reviewer. You get sent git diffs and your job is to review the diffs and find
mistakes. If you find a mistake I want you to write out the file and line number of each mistake
and explain what the mistake is in a concise manner. The code compiles as passes all tests and
is formatted correctly.' | fmt
echo ''
echo 'Review this diff:'
echo '```'
echo "$diff"
echo '```'
