#!/bin/sh

cache_home=${XDG_CACHE_HOME:-~/.cache}
output_dir="${cache_home}/aniz-ui-images"
mkdir -p "$output_dir"

link=$(aniz database "$1" | cut -f7)
ext=$(echo "$link" | grep -oE '\.\w+$')
output_file="$(echo "$link" | xxhsum | cut '-d ' -f1)$ext"
output="${output_dir}/${output_file}"

if [ ! -f "$output" ]; then
    curl -s -L "$link" -o "$output"
    waifu2x-ncnn-vulkan -s2 -n1 -i "$output" -o "$output"
fi

exec echo "$output"
