#!/bin/sh

fzf2() {
    ratio=3
    percent=$((100 / ratio))
    fzfimg.sh -m -d '\t' --tiebreak begin --with-nth=1,2,3,4,5 \
        --preview-window="right:${percent}%,border-none" \
        --preview 'draw_preview "$(aniz-ui-download-image {6})"' \
        "$@"
}

images_dir="$HOME/.cache/aniz-ui-images"
mkdir -p "$images_dir"

command=$1
search=$2

while true; do
    picks=$(mktemp -p /tmp aniz-ui-picks.XXXXXXXXXX)
    case $command in
        database) aniz database |
            fzf2 --disabled --bind 'change:reload:aniz database --search {q}' |
            cut -f5,6 >"$picks" ;;
        list) aniz list |
            fzf2 --tabstop 4 --disabled --bind 'change:reload:aniz list --search {q}' |
            cut -f5,6 >"$picks" ;;
        update)
            aniz list | cut -f6 | xargs -d'\n' aniz update
            exit 0
            ;;
        *)
            wait
            rm "$picks"
            exit 0
            ;;
    esac
    [ -s "$picks" ] || {
        rm "$picks"
        exit 0
    }

    while true; do
        choice=$(printf '
watch-episode
complete
drop
plan-to-watch
put-on-hold
start-watching
update
remove
watch
torrent
view
' | sed '/^$/d' | fzf | cut -f1)
        case $choice in
            view) cut -f2 "$picks" | xargs -d '\n' systemd-run --user open ;;
            torrent)
                cut -f1 "$picks" | jq -sRr @uri |
                    sed 's#%0A#\n#g' |
                    sed 's#^#https://nyaa.si/?q=#' |
                    xargs -d '\n' systemd-run --user open
                ;;
            watch)
                cut -f1 "$picks" | jq -sRr @uri |
                    sed 's#%0A#\n#g' |
                    sed 's#^#https://aniwave.to/filter?keyword=#' |
                    xargs -d '\n' systemd-run --user open
                ;;
            complete | drop | plan-to-watch | put-on-hold | start-watching | update | remove | watch-episode)
                cut -f2 "$picks" | xargs -d'\n' aniz "$choice"
                ;;
            *) break ;;
        esac
    done

    rm "$picks"
done
