#!/bin/sh

fzf2() {
    fzf-img -m -d '\t' --tiebreak begin --with-nth=1,2,3,4,5 \
        --preview 'draw "$(aniz-ui-download-image {6})"' \
        "$@"
}

picks=$(mktemp -t aniz-ui-picks.XXXXXXXXXX)
aniz "$1" |
    fzf2 --disabled --bind "change:reload:aniz '$1' --search {q}" |
    cut -f5,6 >"$picks"

[ -s "$picks" ] || {
    rm "$picks"
    exit 0
}

while true; do
    choice=$(printf '
watch-episode
complete
drop
plan-to-watch
put-on-hold
start-watching
update
remove
watch
torrent
view
' | sed '/^$/d' | fzf)
    case $choice in
        view) cut -f2 "$picks" | xargs '-d\n' systemd-run --user open ;;
        torrent)
            cut -f1 "$picks" | jq -sRr @uri |
                sed 's#%0A#\n#g' |
                sed 's#^#https://nyaa.si/?q=#' |
                xargs '-d\n' systemd-run --user open
            ;;
        watch)
            cut -f1 "$picks" | jq -sRr @uri |
                sed 's#%0A#\n#g' |
                sed 's#^#https://aniwave.to/filter?keyword=#' |
                xargs '-d\n' systemd-run --user open
            ;;
        complete | drop | plan-to-watch | put-on-hold | start-watching | update | remove | watch-episode)
            cut -f2 "$picks" | xargs '-d\n' aniz list "$choice"
            ;;
        *) break ;;
    esac
done

rm "$picks"
