#!/bin/sh

cache_home=${XDG_CACHE_HOME:-~/.cache}
output_dir="${cache_home}/aniz-ui-images"
mkdir -p "$output_dir"

link=$(aniz database "$1" | cut -f7)
output_file=$(echo "$link" | xxhsum | cut '-d ' -f1)
output="${output_dir}/${output_file}"

cache -o "$output" -- curl -s -L "$link" -o "$output"
exec echo "$output"
