#!/bin/sh

fzf2() {
    ratio=3
    percent=$((100 / ratio))
    fzfimg.sh -m -d '\t' --tiebreak begin --with-nth=1,2,3,4,5 \
        --preview-window="right:${percent}%,border-none" \
        --preview 'draw_preview "$(cache -- aniz-ui download-image {6} "{{output}}")"' \
        "$@"
}

command=$1
search=$2
output=$3

while true; do
    picks=$(mktemp)
    case $command in
        database) aniz database | rg "$search" | fzf2 | cut -f5,6 >"$picks" ;;
        list) aniz list | rg "$search" | fzf2 --tabstop 4 | cut -f5,6 >"$picks" ;;
        copy)
            aniz database | rg "$search" | fzf2 | xsel -b
            exit 0
            ;;
        update)
            aniz list | cut -f6 | xargs -d'\n' aniz update
            exit 0
            ;;
        download-image)
            aniz database "$search" | cut -f7 | xargs -d'\n' -I% curl -L % -o "$output"
            exit 0
            ;;
        *)
            wait
            rm "$picks"
            exit 0
            ;;
    esac
    [ -s "$picks" ] || {
        rm "$picks"
        break
    }

    while true; do
        choice=$(printf '
watch-episode
complete
drop
plan-to-watch
put-on-hold
start-watching
update
remove
torrent
view
' | sed '/^$/d' | fzf | cut -f1)
        case $choice in
            view) cut -f2 "$picks" | xargs -d '\n' tsp "$BROWSER" ;;

            torrent)
                cut -f1 "$picks" |
                    sed -e 's/ /+/g' -e 's#^#https://nyaa.si/?q=#' |
                    xargs -d '\n' tsp "$BROWSER"
                ;;
            complete | drop | plan-to-watch | put-on-hold | start-watching | update | remove | watch-episode)
                cut -f2 "$picks" | xargs -d'\n' aniz "$choice" 2>/tmp/dump
                ;;
            *) break ;;
        esac
    done

    rm "$picks"
done
