#!/bin/sh -e

xrandr=$(mktemp)
output=$(mktemp)
mode=$(mktemp)
rate=$(mktemp)

xrandr >"$xrandr"

rg <"$xrandr" '^([^ ]*) connected' -o -r '$1' >"$output"
rg <"$xrandr" --multiline '^[^ ]* connected .*\n\s+([^ ]+)' -o -r '$1' >"$mode"
rg <"$xrandr" --multiline '^[^ ]* connected .*\n\s+[^ ]+\s+(.*)' -o -r '$1' |
    sed -E 's/\*|\+//g' |
    while read -r line; do
        echo "$line" | sed 's/[ ][ ]*/\n/g' | sort -h | tail -n1
    done >"$rate"

paste "$output" "$mode" "$rate" |
    nawk '{printf "--output\n%s\n--mode\n%s\n--rate\n%s\n", $1, $2, $3 }' |
    xargs -d'\n' xrandr

rm "$xrandr" "$output" "$mode" "$rate"
