#!/bin/sh

cmd=$*
[ -z "$cmd" ] && [ -f 'Cargo.toml' ] &&
    cmd='cargo clippy && cargo build'
[ -z "$cmd" ] && [ -f 'build.zig' ] &&
    cmd='zig build --prominent-compile-errors'

fd \
    -e c \
    -e cc \
    -e cfg \
    -e cpp \
    -e cs \
    -e css \
    -e graphql \
    -e h \
    -e hh \
    -e hpp \
    -e html \
    -e java \
    -e js \
    -e kt \
    -e lua \
    -e py \
    -e rs \
    -e toml \
    -e toml \
    -e yml \
    -e zig \
    --exclude 'zig-cache' | exec entr -crs "$cmd"
