#!/bin/sh

out=$1
picker=${2:-fzf}
preview=$3

pick() {
    "$picker" --preview-window="right:50%,border-none" --preview "$preview" "$@"
}

new_category="<new category>"
categories=$(fd . "$out" --type f | sed 's|.*/||' | cut -d, -f2 | sort -u)
category=$({
    echo "$new_category"
    echo "$categories"
} | pick)

if [ "$category" = "$new_category" ]; then
    category=$(printf "" | pick --print-query)
fi
if [ -z "$category" ]; then
    exit 1
fi

echo "$category"
