#!/bin/sh

picker=${1:-fzf}
preview=$2

pick() {
    "$picker" --preview-window="right:75%,border-none" --preview "$preview" "$@"
}

done_it="<done>"
new_tag="<new tag>"
exit_it="<exit>"

tags_file="$XDG_CONFIG_HOME/categories"
mkdir -p "$(dirname "$tags_file")"
tags=$(cat "$tags_file")

picked_tags=$(mktemp -p /tmp categorize-pick-tags.XXXXXXXXXX)
while true; do
    tag=$({
        echo "$done_it"
        echo "$exit_it"
        echo "$new_tag"
        echo "$tags"
    } | pick)

    if [ "$tag" = "$exit_it" ]; then
        exit 1
    fi
    if [ "$tag" = "$done_it" ]; then
        break
    fi
    if [ "$tag" = "$new_tag" ]; then
        tag=$(printf "" | pick --print-query)
        if [ "$tag" != "" ]; then
            {
                echo "$tag"
                cat "$tags_file"
            } | sort -u | sponge "$tags_file"
        fi
    fi
    if [ -z "$tag" ]; then
        continue
    fi

    echo "$tag" >>"$picked_tags"
    tags=$(echo "$tags" | sed "/^$tag$/d")
done

cat "$picked_tags"
rm "$picked_tags"
