#!/bin/sh

to_categorize=$(mktemp -t 'categorize-missing-bulk.XXXXXXXX')

fd . "$1" |
    rg -v '/0-n?sfw,1-[^/]*$' |
    fzf-img -m >"$to_categorize"

if [ -z "$to_categorize" ]; then
    exit 1
fi

fzf-img-mpv-window "$(head -n1 "$to_categorize")" &
mpv_pid=$!
sleep 0.1

name=$(categorize-namer "" "fzf-img-no-mpv" "")
if [ -z "$name" ]; then
    kill "$mpv_pid"
    exit 1
fi

xargs '-d\n' -I% categorize-rename % "$1" "$name" <"$to_categorize"
rm "$to_categorize"

kill "$mpv_pid"
