#!/bin/sh

image=$1
out=$2

escaped_image=$(echo "$image" | sed "s/'/'\"'\"'/g")
name=$(categorize-namer "" "fzf-img" "draw '$escaped_image'")
if [ -z "$name" ]; then
    exit 255
fi

categorize-rename "$image" "$out" "$name"
