#!/bin/sh

picker=${1:-fzf}
preview=$2

picked_tags=$(categorize-pick-tags "$picker" "$preview")
if [ -z "$picked_tags" ]; then
    exit 1
fi

picked_tags=$(echo "$picked_tags" | sort -u | tr '\n' ',' | sed 's/,$//')
echo "$picked_tags" | sed 's/,$//'
