#!/bin/sh -e

# Replaces colors defined in themable config files with colors defined in COLOR0 to COLOR15
# environment variables.

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

sed -i "$config_home/foot/foot.ini" \
    -e "s/background=[a-zA-Z0-9]*/background=$COLOR0/" \
    -e "s/foreground=[a-zA-Z0-9]*/foreground=$COLOR5/" \
    -e "s/regular0=[a-zA-Z0-9]*/regular0=$COLOR0/" \
    -e "s/regular1=[a-zA-Z0-9]*/regular1=$COLOR8/" \
    -e "s/regular2=[a-zA-Z0-9]*/regular2=$COLOR11/" \
    -e "s/regular3=[a-zA-Z0-9]*/regular3=$COLOR10/" \
    -e "s/regular4=[a-zA-Z0-9]*/regular4=$COLOR13/" \
    -e "s/regular5=[a-zA-Z0-9]*/regular5=$COLOR14/" \
    -e "s/regular6=[a-zA-Z0-9]*/regular6=$COLOR12/" \
    -e "s/regular7=[a-zA-Z0-9]*/regular7=$COLOR5/" \
    -e "s/bright0=[a-zA-Z0-9]*/bright0=$COLOR3/" \
    -e "s/bright1=[a-zA-Z0-9]*/bright1=$COLOR8/" \
    -e "s/bright2=[a-zA-Z0-9]*/bright2=$COLOR11/" \
    -e "s/bright3=[a-zA-Z0-9]*/bright3=$COLOR10/" \
    -e "s/bright4=[a-zA-Z0-9]*/bright4=$COLOR13/" \
    -e "s/bright5=[a-zA-Z0-9]*/bright5=$COLOR14/" \
    -e "s/bright6=[a-zA-Z0-9]*/bright6=$COLOR12/" \
    -e "s/bright7=[a-zA-Z0-9]*/bright7=$COLOR7/"

sed -i "$config_home/dunst/dunstrc" \
    -e "s/frame_color = \"#[a-zA-Z0-9]*\"/frame_color = \"#$COLOR3\"/" \
    -e "s/background = \"#[a-zA-Z0-9]*\" # urgency_low/background = \"#$COLOR0\" # urgency_low/" \
    -e "s/foreground = \"#[a-zA-Z0-9]*\" # urgency_low/foreground = \"#$COLOR3\" # urgency_low/" \
    -e "s/background = \"#[a-zA-Z0-9]*\" # urgency_normal/background = \"#$COLOR0\" # urgency_normal/" \
    -e "s/foreground = \"#[a-zA-Z0-9]*\" # urgency_normal/foreground = \"#$COLOR5\" # urgency_normal/" \
    -e "s/background = \"#[a-zA-Z0-9]*\" # urgency_critical/background = \"#$COLOR0\" # urgency_critical/" \
    -e "s/foreground = \"#[a-zA-Z0-9]*\" # urgency_critical/foreground = \"#$COLOR8\" # urgency_critical/"

sed -i "$config_home/waybar/config" \
    -e "s/<span color='#[a-zA-Z0-9]*'> /<span color='#$COLOR11'> /" \
    -e "s/<span color='#[a-zA-Z0-9]*'>▁/<span color='#$COLOR11'>▁/" \
    -e "s/<span color='#[a-zA-Z0-9]*'>▂/<span color='#$COLOR11'>▂/" \
    -e "s/<span color='#[a-zA-Z0-9]*'>▃/<span color='#$COLOR10'>▃/" \
    -e "s/<span color='#[a-zA-Z0-9]*'>▄/<span color='#$COLOR10'>▄/" \
    -e "s/<span color='#[a-zA-Z0-9]*'>▅/<span color='#$COLOR9'>▅/" \
    -e "s/<span color='#[a-zA-Z0-9]*'>▆/<span color='#$COLOR9'>▆/" \
    -e "s/<span color='#[a-zA-Z0-9]*'>▇/<span color='#$COLOR8'>▇/" \
    -e "s/<span color='#[a-zA-Z0-9]*'>█/<span color='#$COLOR8'>█/"

sed -i "$config_home/waybar/colors.css" \
    -e "s/color0 #[a-zA-Z0-9]*;/color0 #$COLOR0;/" \
    -e "s/color1 #[a-zA-Z0-9]*;/color1 #$COLOR1;/" \
    -e "s/color2 #[a-zA-Z0-9]*;/color2 #$COLOR2;/" \
    -e "s/color3 #[a-zA-Z0-9]*;/color3 #$COLOR3;/" \
    -e "s/color4 #[a-zA-Z0-9]*;/color4 #$COLOR4;/" \
    -e "s/color5 #[a-zA-Z0-9]*;/color5 #$COLOR5;/" \
    -e "s/color6 #[a-zA-Z0-9]*;/color6 #$COLOR6;/" \
    -e "s/color7 #[a-zA-Z0-9]*;/color7 #$COLOR7;/" \
    -e "s/color8 #[a-zA-Z0-9]*;/color8 #$COLOR8;/" \
    -e "s/color9 #[a-zA-Z0-9]*;/color9 #$COLOR9;/" \
    -e "s/color10 #[a-zA-Z0-9]*;/color10 #$COLOR10;/" \
    -e "s/color11 #[a-zA-Z0-9]*;/color11 #$COLOR11;/" \
    -e "s/color12 #[a-zA-Z0-9]*;/color12 #$COLOR12;/" \
    -e "s/color13 #[a-zA-Z0-9]*;/color13 #$COLOR13;/" \
    -e "s/color14 #[a-zA-Z0-9]*;/color14 #$COLOR14;/" \
    -e "s/color15 #[a-zA-Z0-9]*;/color15 #$COLOR15;/"

sed -i "$config_home/rofi/colors.rasi" \
    -e "s/color0: #[a-zA-Z0-9]*;/color0: #$COLOR0;/" \
    -e "s/color1: #[a-zA-Z0-9]*;/color1: #$COLOR1;/" \
    -e "s/color2: #[a-zA-Z0-9]*;/color2: #$COLOR2;/" \
    -e "s/color3: #[a-zA-Z0-9]*;/color3: #$COLOR3;/" \
    -e "s/color4: #[a-zA-Z0-9]*;/color4: #$COLOR4;/" \
    -e "s/color5: #[a-zA-Z0-9]*;/color5: #$COLOR5;/" \
    -e "s/color6: #[a-zA-Z0-9]*;/color6: #$COLOR6;/" \
    -e "s/color7: #[a-zA-Z0-9]*;/color7: #$COLOR7;/" \
    -e "s/color8: #[a-zA-Z0-9]*;/color8: #$COLOR8;/" \
    -e "s/color9: #[a-zA-Z0-9]*;/color9: #$COLOR9;/" \
    -e "s/color10: #[a-zA-Z0-9]*;/color10: #$COLOR10;/" \
    -e "s/color11: #[a-zA-Z0-9]*;/color11: #$COLOR11;/" \
    -e "s/color12: #[a-zA-Z0-9]*;/color12: #$COLOR12;/" \
    -e "s/color13: #[a-zA-Z0-9]*;/color13: #$COLOR13;/" \
    -e "s/color14: #[a-zA-Z0-9]*;/color14: #$COLOR14;/" \
    -e "s/color15: #[a-zA-Z0-9]*;/color15: #$COLOR15;/"
