#!/bin/sh
case $1 in
    *.jpg | *.jpeg | *.png)
        converted=$(mktemp -t 'converted.XXXXXXXX.jxl')
        output=$(echo "$1" | sed 's/\.[a-zA-Z]*$/.jxl/')
        cjxl "$1" "$converted" -q 100
        if mv -n "$converted" "$output"; then
            rm "$1"
        else
            rm "$converted"
        fi

        thumbnail "$output" 2>/dev/null >/dev/null
        echo "$output"
        ;;
    *)
        echo "$1"
        ;;
esac
