#!/bin/sh
case $1 in
    *.jxl)
        echo "$1"
        ;;
    *)
        converted=$(mktemp -t 'converted.XXXXXXXX.jxl')
        output=$(echo "$1" | sed 's/\.[a-zA-Z]*$/.jxl/')
        cjxl "$1" "$converted" -q 100
        if mv -n "$converted" "$output"; then
            rm "$1"
        else
            rm "$converted"
        fi
        echo "$output"
        ;;
esac
