#!/bin/sh

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
yay -Q "$1" || exit 1

sed -i "/^${1}$/d" "$config_home/installed-programs"
printf "%s\n" "$1" >>"$config_home/essential-programs"

sort -u "$config_home/essential-programs" |
    exec sponge "$config_home/essential-programs"
