#!/bin/sh
config=$XDG_CONFIG_HOME
yay -Q "$1" || exit 1

sed -i "/^${1}$/d" "${config}/installed-programs"
printf "%s\n" "$1" >>"${config}/essential-programs"

sort -u "${config}/essential-programs" |
    exec sponge "${config}/essential-programs"
