#!/bin/sh -e
# Export currently installed packages back to dotfiles
# This allows for imperative package management with periodic syncing to git

command -v pacman >/dev/null &&
  pacman -Qnqe >"$HOME/.config/pkgs/arch"
command -v pacman >/dev/null &&
  pacman -Qmqe >"$HOME/.config/pkgs/aur"

command -v dipm >/dev/null &&
  dipm list installed | cut -f1 | sort >"$HOME/.config/pkgs/dipm"
