#!/bin/sh -e

for file in "$@"; do
    if ! [ -f "$file" ]; then
        continue
    fi

    ext=$(file "$file" --extension | rg -o '.*: (\w+)*' -r '$1')
    name=$(echo "$file" | sed 's/\.[^.]*$//')
    new_file_name="$name.$ext"
    if [ "$file" = "$new_file_name" ]; then
        continue
    fi

    mv -i "$file" "$new_file_name"
done
