#!/bin/sh

if [ -d "$1" ]; then
    fd . --base-directory "$1" --maxdepth 1
    exit 0
fi

mime=$(file --brief --dereference --mime -- "$1" | cut '-d;' -f1)
case $mime in
    image/png | image/jpeg) chafa -s "${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}" "$1" ;;
    *) bat --color=always --line-range ":$FZF_PREVIEW_LINES" "$1" ;;
esac
