#!/usr/bin/env bash

mpv_ipc=$(mktemp -t fzf-img.XXXXXXXXXX)
mpv --no-terminal --force-window --idle --loop \
    --video-unscaled=downscale-big \
    --wayland-app-id=nofocus \
    --focus-on=never \
    --input-ipc-server="$mpv_ipc" &
mpv_pid=$!

sleep 0.1 # Wait for mpv to start

fzf-img-no-mpv "$mpv_ipc" "$@"

kill "$mpv_pid"
