#!/bin/sh

# We might run this before the environment has been setup
eval "$(grep '^COLOR' "$HOME"/.config/environment.d/* |
    sed 's/^/export /')"

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

template_dir="$config_home/template"

mkdir -p "$config_home/dunst"
mkdir -p "$config_home/foot"
mkdir -p "$config_home/waybar"
base16 "$template_dir/foot.ini" >"$config_home/foot/foot.ini"
base16 "$template_dir/dunstrc" >"$config_home/dunst/dunstrc"
base16 "$template_dir/waybar.css" >"$config_home/waybar/style.css"
base16 "$template_dir/waybar.json" >"$config_home/waybar/config"

waybar_cpus=$(lscpu |
    grep -F 'On-line CPU(s) list:' |
    grep -Eo '[0-9]+-[0-9]+' |
    tr '-' '\n' |
    xargs '-d\n' seq |
    sed -e 's/^/{icon/' -e 's/$/}/' |
    tr -d '\n')

sed -i "s/{{waybar-cpus}}/$waybar_cpus/g" "$config_home/waybar/config"
