#!/bin/sh

# We might run this before the environment has been setup
eval "$(grep '^COLOR' "$HOME"/.config/environment.d/* |
    sed 's/^/export /')"

template_dir="$HOME/.config/template"

mkdir -p "$XDG_CONFIG_HOME/dunst"
mkdir -p "$XDG_CONFIG_HOME/foot"
mkdir -p "$XDG_CONFIG_HOME/waybar"
base16 "$template_dir/foot.ini" >"$XDG_CONFIG_HOME/foot/foot.ini"
base16 "$template_dir/dunstrc" >"$XDG_CONFIG_HOME/dunst/dunstrc"
base16 "$template_dir/waybar.css" >"$XDG_CONFIG_HOME/waybar/style.css"
base16 "$template_dir/waybar.json" >"$XDG_CONFIG_HOME/waybar/config"

waybar_cpus=$(lscpu |
    grep -F 'On-line CPU(s) list:' |
    grep -Eo '[0-9]+-[0-9]+' |
    tr '-' '\n' |
    xargs '-d\n' seq |
    sed -e 's/^/{icon/' -e 's/$/}/' |
    tr -d '\n')

sed -i "s/{{waybar-cpus}}/$waybar_cpus/g" "$XDG_CONFIG_HOME/waybar/config"
