#!/bin/sh
# Setup rules to have 10 workspaces per monitor.
# Monitor 1 will have 1-10, 2 will have 11-20 and repeat.
# We then have other scripts that switches workspace based on the focused monitor.
# This mimics how bspwm works.
hyprland-monitor-workspaces |
    exec awk '{ printf "workspace=%s,monitor:%s\n", $1, $2 }' >"$HOME/.config/hypr/workspace.conf"
