#!/bin/sh
# This command works the same as `hyprctl dispatch movetoworkspace $1`, but it switches to a workspace
# on the same monitor.
workspace=$(hyprland-to-real-workspace "$1")
exec hyprctl dispatch "hl.dsp.window.move({ workspace = $workspace })"
