#!/bin/sh
monitors name |
    xargs '-d\n' yes | # Generates infite pairs of monitors, seperated by spaces
    head -n10 |        # Pick 10
    tr ' ' '\n' |      # Flatten
    sort |             # With it sorted, we now have 10 x monitor1, 10 x monitor2 ...
    exec nl -n ln      # We use nl to give each line a unique id
