#!/bin/sh
# Translates a workspace id that is relative to the focused monitor to the real workspace id.
# The workspace rules have been setup by `hyprland-setup-workspace-rules` so that this is possible.
focused_monitor=$(
    hyprctl monitors -j |
        jq -r '.[] | select(.focused) | .name'
)
hyprland-monitor-workspaces |
    grep -F "$focused_monitor" |
    sed "${1}!d" |
    exec cut -f1
