#!/bin/sh

opener=$(file -0 -F ' ' --mime-type -L "$@" | sed 's/\x0\s*/\t/' | opener | sort -u)

if [ -z "$opener" ]; then
    exit 1
fi
if [ "$(echo "$opener" | wc -l)" -ne 1 ]; then
    exit 1
fi

systemd-run -d --user $opener "$@"
