#!/bin/sh

repo='PathOfBuildingCommunity/PathOfBuilding'
pob_dir="$XDG_CACHE_HOME/pob"

if ! [ -f "$pob_dir/Path of Building.exe" ]; then
    mkdir -p "$pob_dir"

    latest_release=$(gh release list -L 1 -R "$repo" | cut -f3)
    gh release download "$latest_release" -R "$repo" -p '*Portable*' -D "$pob_dir"
    fd . "$pob_dir" -e zip -x unzip {} -d "$pob_dir"
fi

wine "$pob_dir/Path of Building.exe"
