#!/bin/sh -e

command=$1
dir=$2
head_of_queue="$dir/head"
tail_of_queue="$dir/tail"

mkdir -p "$dir"
if ! [ -f "$head_of_queue" ]; then
    echo '0' >"$head_of_queue"
fi
if ! [ -f "$tail_of_queue" ]; then
    echo '0' >"$tail_of_queue"
fi

case $command in
    dequeue)
        head=$(cat "$head_of_queue")
        new_head=$((head + 1))
        cat "$dir/$new_head"
        rm "$dir/$new_head"
        echo "$new_head" >"$head_of_queue"
        ;;
    enqueue)
        tail=$(cat "$tail_of_queue")
        new_tail=$((tail + 1))
        cat - >"$dir/$new_tail"
        echo "$new_tail" >"$tail_of_queue"
        ;;
    show)
        head=$(cat "$head_of_queue")
        i=$((head + 1))
        while cat "$dir/$i" 2>/dev/null; do
            i=$((i + 1))
        done
        ;;
esac
