#!/bin/sh

# sudo setcap cap_sys_admin+ep '/usr/bin/gsr-kms-server'

date=$(date '+%y-%m-%dT%H-%M-%S')
sink=$(pactl get-default-sink)
src=$(pactl get-default-source)
videos_dir=$(xdg-user-dir VIDEOS)
container='mp4'

output="${videos_dir}/${date}.${container}"
echo "$output"

exec gpu-screen-recorder -w DP-1 -k av1 -q ultra -ac opus -f 60 -c "${container}" \
    -o "${output}" -a "${sink}.monitor" -a "${src}"
