#!/bin/sh

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
config_dir="$config_home/rss"
urls_file="$config_dir/urls"

for entry in "$@"; do
    echo "$entry"
done >>"$urls_file"

sort -u "$urls_file" | exec sponge "$urls_file"
