#!/bin/sh

channel_link=$1
channel_details=$(mktemp -t 'rss-youtube-add.XXXXXXXX')
yt-dlp -j "$channel_link" -I 1:1 >"$channel_details"

channel_id=$(jq .channel_id -r "$channel_details")
channel_name=$(jq .channel -r "$channel_details")
rm "$channel_details"

rss-add "# $channel_name"
rss-add "$(printf 'https://www.youtube.com/feeds/videos.xml?channel_id=%s' "$channel_id")"
