#!/bin/sh

check_and_add() {
    link=$1
    rss=$2

    open "$link" >/dev/null 2>/dev/null

    printf "Do you want to add '%s' [y/N]\n" "$rss"
    read -r answer
    if [ "$answer" = "y" ]; then
        rss-add "$rss"
    fi
}

check_and_add "https://konachan.com/post?tags=$1" \
    "https://konachan.com/post?tags=$1"

check_and_add "https://safebooru.org/index.php?page=post&s=list&tags=$1" \
    "https://safebooru.org/index.php?page=cooliris&tags=$1"

check_and_add "https://yande.re/post?tags=$1" \
    "https://yande.re/post/atom?tags=$1"
