#!/bin/sh

urls_file="$(rss-dirs urls)"

for entry in "$@"; do
    echo "$entry"
done >>"$urls_file"

sort -u "$urls_file" | exec sponge "$urls_file"
git -C "$(dirname "$urls_file")" commit -a -m "Add"
