#!/bin/sh

urls_file="$(rss-dirs urls)"
urls_old_file="$(rss-dirs urls-old)"

to_remove=$(mktemp -t 'rss-remove.XXXXXXXX')
for entry in "$@"; do
    echo "$entry"
done >>"$to_remove"

{
    cat "$urls_old_file"
    grep -Ff "$to_remove" "$urls_file"
} | sort -u | sponge "$urls_old_file"
grep -vFf "$to_remove" "$urls_file" | sponge "$urls_file"

rm "$to_remove"
