#!/bin/sh

urls_file="$(rss-dirs urls)"
read_dir="$(rss-dirs read)"
unread_dir="$(rss-dirs unread)"

# We need to use another IFS because using \t does not allow empty fields
IFS=$(printf '\a')

{
    rss-download-extra-feeds
    rss-download-feed "$urls_file" | sfeed
} | tr '\t' '\a' |
    while read -r timestamp title link content content_type id author enclosure; do
        id=$(printf '%s-%s-%s' "$id" "$link" "$enclosure" | xxhsum | cut -d' ' -f1)
        [ -e "$unread_dir/$id" ] && {
            touch "$unread_dir/$id"
            continue
        }
        [ -e "$read_dir/$id" ] && {
            touch "$read_dir/$id"
            continue
        }

        printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n' \
            "$timestamp" "$title" "$link" "$content" "$content_type" "$author" "$enclosure" \
            >"$unread_dir/$id"
    done

# Older than 10d posts will be deleted
fd . "$read_dir" --older 10d -x rm

# Auto read youtube shorts
rss-list unread | cut -f1,4 |
    rg 'https://www.youtube.com/shorts/' | cut -f1 |
    nargs -I% mv % "$read_dir"
