#!/bin/sh

output=$(mktemp -t -d 'rss-download-feed.XXXXXXXX')

cut -f1 "$1" |
    sort -R |
    sed '/^$/d' |
    nl -w1 |
    sed 's/^/-o\t/' |
    xargs curl -v --rate '10/h' --retry 5 --retry-delay 10 --output-dir "$output"

find "$output" -type f -print0 |
    xargs -0 cat

exec rm -r "$output"
