#!/bin/sh

t=$(printf '\t')

curl 'https://db.hashblen.com/codes' |
    jq '.zzz[].code' -r |
    rg '^.*$' -r "$t\$0 - Zenless Zone Zero Code${t}https://zenless.hoyoverse.com/redemption\?code=\$0$t$t$t\$0${t}Zenless Zone Zero$t"

{
    curl 'https://wallhaven.cc/api/v1/search?sorting=toplist&topRange=1w'
    curl 'https://wallhaven.cc/api/v1/search?sorting=toplist&topRange=1M'
    curl 'https://wallhaven.cc/api/v1/search?sorting=toplist&topRange=1y'
} | jq -r '.data[] | "", .id + " - Wallhaven", .path, "", "", .id, "Wallhaven", ""' |
    paste - - - - - - - -
