#!/bin/sh -e

command=$1
dir=$2
top_of_stack="$dir/top"

mkdir -p "$dir"
if ! [ -h "$top_of_stack" ]; then
    ln -sf "0" "$top_of_stack"
fi

top=$(readlink "$top_of_stack")

case $command in
    pop)
        readlink "$dir/$top"
        rm "$dir/$top"
        ln -sf "$((top - 1))" "$top_of_stack"
        ;;
    push)
        new_top=$((top + 1))
        ln -s "$(cat -)" "$dir/$new_top"
        ln -sf "$new_top" "$top_of_stack"
        ;;
    show)
        i=1
        while readlink "$dir/$i" 2>/dev/null; do
            i=$((i + 1))
        done
        ;;
esac
