#!/bin/sh

picked_tags=$(echo "$1" | tr ',' '\n')
picker=${2:-fzf}
preview=$3

pick() {
    "$picker" --preview "$preview" "$@"
}

done_it="<done>"
new_tag="<new tag>"
exit_it="<exit>"

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

tags_dir="$config_home/tag"
tags_file="$tags_dir/tags"

mkdir -p "$tags_dir"
touch "$tags_file"
tags=$(cat "$tags_file")

picked_tags_file=$(mktemp -t tag-pick-tags.XXXXXXXXXX)
echo "$picked_tags" >"$picked_tags_file"

while true; do
    current="<$(tr '\n' ',' <"$picked_tags_file" | sed -e 's/,$//' -e 's/^,//')>"
    tag=$({
        echo "$done_it"
        echo "$exit_it"
        echo "$new_tag"
        echo "$current"
        echo "$tags"
    } | pick)

    case $tag in
        "") continue ;;
        "$current") continue ;;
        "$exit_it") exit 1 ;;
        "$done_it") break ;;
        "$new_tag")
            tag=$(printf "" | pick --print-query)
            if [ "$tag" != "" ]; then
                {
                    echo "$tag"
                    cat "$tags_file"
                } | sort -u | sponge "$tags_file"
            fi
            echo "$tag" >>"$picked_tags_file"
            ;;
        *)
            echo "$tag" >>"$picked_tags_file"
            tags=$(echo "$tags" | sed "/^$tag$/d")
            ;;
    esac
done

sed '/^$/d' "$picked_tags_file"
rm "$picked_tags_file"
