#!/bin/sh

in=$1
out=$2
name=$3
ext=$(file "$in" --extension | rg -o '.*: (\w+)*' -r '$1')
if [ -z "$ext" ]; then
    ext=$(file "$in" --mime-type | rg -o '.*: \w+/(\w+)*' -r '$1')
fi

i=$(fd "$name," "$out" |
    rg -o '\,(\d+)\.[^.]*$' -r '$1' |
    sort -n |
    tail -n1)

i=$((i + 1))
file="$out/$name,$i.$ext"

mv -i "$in" "$file"

echo "$file"
