#!/bin/sh

picked_tags=$1
picker=${2:-fzf}
preview=$3

picked_tags=$(tag-pick-tags "$picked_tags" "$picker" "$preview")
if [ -z "$picked_tags" ]; then
    exit 1
fi

picked_tags=$(echo "$picked_tags" | sort -u | tr '\n' ',' | sed 's/,$//')
echo "$picked_tags" | sed 's/,$//'
