#!/bin/sh

fzf-img-mpv-window &
mpv_pid=$!
sleep 0.1 # Wait for mpv to start

for image in "$@"; do
    image_escaped=$(echo "$image" | escape-sh-str-quote)
    tags_picked=$(tagger-get-taglist | fzf-img-no-mpv -m --preview "draw '$image_escaped'")
    if [ -z "$tags_picked" ]; then
        break
    fi

    if ! tagger-is-tagged "$image"; then
        image=$(tagger-prepare "$image")
    fi

    echo "$tags_picked" | nargs tagger-add-tags "$image"
done

kill "$mpv_pid"
