#!/bin/sh

for image in "$@"; do
    image_escaped=$(echo "$image" | escape-sh-str-quote)
    tags_picked=$(tagger-get-taglist | fzf -m \
        --bind "start:preview:fzf-preview '$image_escaped'" \
        --bind "resize:preview:fzf-preview '$image_escaped'")
    if [ -z "$tags_picked" ]; then
        break
    fi

    if ! tagger-is-tagged "$image"; then
        image=$(tagger-prepare "$image")
    fi

    echo "$tags_picked" | nargs tagger-add-tags "$image"
done
