#!/bin/sh

get_tags() {
    file=$1

    if ! echo "$file" | grep -E '^([a-zA-Z0-9_:-]+,)*[0-9]+\.\w+$'; then
        echo "File '$file' is not tagged. To prepare file for tagging, run:" >&2
        echo "    tagger prepare '$file'" >&2
        exit 1
    fi

    echo "$file" | tr ',' '\n' | head -n -1
}

rename() {
    file=$1
    file_tags=$2

    if ! [ -f "$file" ]; then
        echo "File '$file' not found" >&2
        exit 1
    fi

    file_dir=$(dirname "$file")
    file_basename=$(basename "$file")
    file_name=$(echo "$file_basename" | cut -d. -f1)
    file_ext=$(echo "$file_basename" | sed "s#^$file_name##")

    i=0
    while ! mv -n "$file" "${file_dir}/${file_tags}${i}${file_ext}" 2>/dev/null; do
        i=$((i + 1))
    done

    echo "${file_dir}/${file_tags}${i}${file_ext}"
}

print_args_nl() {
    for arg in "$@"; do
        printf '%s\n' "$arg"
    done
}

add_tags() {
    file=$1
    shift

    file_tags=$({
        get_tags "$file"
        print_args_nl "$@"
    } | sort -u | tr '\n' ',')

    rename "$file" "$file_tags"
}

remove_tags() {
    file=$1
    shift

    tags_to_remove=$(mktemp -t 'tagger.XXXXXXXX')
    print_args_nl "$@" >"$tags_to_remove"

    file_tags=$(get_tags "$file" |
        grep -v -F -f "$tags_to_remove" |
        tr '\n' ',')

    rename "$file" "$file_tags"
}

prepare_tags() {
    for file in "$@"; do
        rename "$file" ""
    done
}

command=$1
shift
case $command in
    add) add_tags "$@" ;;
    remove) remove_tags "$@" ;;
    tags) get_tags "$@" ;;
    prepare) prepare_tags "$@" ;;
    *) ;;
esac
