#!/bin/sh -e
paru -Syu --noconfirm
paru -Sc --noconfirm
paru -c --noconfirm
dipm update

zig version
install-zig-project "$HOME/repo/forks/zls/" &
install-zig-project "$HOME/repo/own/aniz/" &
install-zig-project "$HOME/repo/own/cache/" &
wait
