#!/bin/sh

old_file_names=$(mktemp)
new_file_names=$(mktemp)

for f in "$@"; do
    printf "%s\n" "$f"
done | tee "$old_file_names" >"$new_file_names"

$EDITOR "$new_file_names"

IFS=$(printf '\a')
paste -d "$IFS" "$old_file_names" "$new_file_names" |
    nawk -F "$IFS" '$1 != $2' |
    while read -r from to; do
        mv -n "$from" "$to"
    done

exec rm "$old_file_names" "$new_file_names"
