#!/bin/sh

wallpapers_on_screen="/tmp/wallpapers-on-screen"
monitors=$(mktemp -t 'wall.monitors.XXXXXXXX')
wallpapers=$(mktemp -t 'wall.wallpapers.XXXXXXXX')

monitors name >"$monitors"
fd . "$1" --type f |
    sort -R >"$wallpapers"

paste "$monitors" "$wallpapers" |
    grep -v '^\s' >"$wallpapers_on_screen"

rm "$monitors" "$wallpapers"
tr <"$wallpapers_on_screen" '\t' '\n' |
    exec xargs '-d\n' -P0 -n2 mpvpaper -p -o '--pause'
