#!/bin/sh

wallpapers_on_screen="/tmp/wallpapers-on-screen"
monitors=$(mktemp -t 'wall.monitors.XXXXXXXX')
wallpapers=$(mktemp -t 'wall.wallpapers.XXXXXXXX')

monitors name >"$monitors"
fd . "$1" --type f |
    sort -R >"$wallpapers"

paste "$monitors" "$wallpapers" |
    grep -v '^\s' |
    # Depending on the file type we pass different options to mpv
    sed -E 's/\.(jxl|png|jpeg)$/.\1\t-o\t--quiet --pause --scale=oversample --panscan=1/' |
    sed -E 's/\.(gif|mp4|webp)$/.\1\t-o\t--quiet --loop --scale=oversample --panscan=1/' |
    cat >"$wallpapers_on_screen"

rm "$monitors" "$wallpapers"

cat "$wallpapers_on_screen" |
    tr '\t' '\n' |
    exec xargs '-d\n' -P0 -n4 mpvpaper -p -o '--pause --scale=oversample'
