#!/bin/sh

cache_file="/tmp/waybar-updates-pkgs"

jo text=0

if ! [ -f "$cache_file" ]; then
    checkupdates >"$cache_file"
fi

updates=$(cat "$cache_file")
jo "text=$(echo "$updates" | wc -l)" "tooltip=$updates"
