#!/bin/sh -e

file=$(mktemp)

cat - >"$file"
zig fmt "$file" 2>/dev/null >/dev/null || true

case $(git remote get-url origin) in
    git@github.com:Hejsil/* | git@github.com:TM35-Metronome/* | '')
        {
            # Sort global constants only for repos I own
            grep -E -n '^((pub\s+)?(const|usingnamespace)).*;$' "$file" | cut -d: -f1 |
                ranges | sed 's/$/!sort/'
            echo 'x'
        } | ex -s "$file"
        ;;
    *) ;;
esac

cat "$file"
rm "$file"
