#!/bin/sh -e

case $(git remote get-url origin) in
    git@github.com:Hejsil/*) ;;
    *)
        zig fmt --stdin
        exit
        ;;
esac

file=$(mktemp)
zig fmt --stdin >"$file"

# Sort global constants
{
    grep -E -n '^((pub\s+)?(const|usingnamespace)).*;$' "$file" | cut -d: -f1 |
        ranges | sed 's/$/!sort/'
    echo 'x'
} | ex -s "$file"

cat "$file"
rm "$file"
