#!/bin/sh -e

cache_home=${XDG_CACHE_HOME:-~/.cache}
git_dir="$cache_home/www_ziglang_org"

if ! [ -d "$git_dir/.git" ]; then
    git clone "https://github.com/ziglang/www.ziglang.org.git" "$git_dir" >/dev/null
fi

cd "$git_dir"

date=$(date +%Y-%m-%d)

if ! [ -f latest_pull ] || [ "$(cat latest_pull)" != "$date" ]; then
    git pull >/dev/null
    echo "$date" >latest_pull
fi

case $1 in
    master) jq -r '.master.version' data/releases.json ;;
    *)
        git log -p data/releases.json |
            grep '"version":' |
            cut '-d"' -f 4 |
            sort -u |
            grep "$1"
        ;;
esac
