#!/bin/sh

timestamp="$(date +%s)"
content=""
content_type=""
enclosure=""
author="Zenless Zone Zero"

curl 'https://hoyo-codes.seriaati.xyz/codes?game=nap' |
    jq -r '.codes[].code' |
    while read -r code; do
        title="$code - Zenless Zone Zero Code"
        link="https://zenless.hoyoverse.com/redemption&code=$code"
        id="$code"
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$timestamp" "$title" "$link" "$content" "$content_type" "$id" "$author" \
            "$enclosure"
    done
