#!/bin/sh

timestamp="$(date +%s)"
content=""
content_type=""
enclosure=""
author="Zenless Zone Zero"

codes_url=$(curl -s 'https://raw.githubusercontent.com/seriaati/hoyo-codes/master/README.md' |
    rg -o 'Zenless Zone Zero: <([^>]*)>' -r '$1')

curl "$codes_url" |
    jq -r '.codes[].code' |
    while read -r code; do
        title="$code - Zenless Zone Zero Code"
        link="https://zenless.hoyoverse.com/redemption&code=$code"
        id="$code"
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$timestamp" "$title" "$link" "$content" "$content_type" "$id" "$author" \
            "$enclosure"
    done
